version: '3.8'

services:
  db:
    image: postgres
    container_name: starwarsdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=starwars
    ports:
      - 5432:5432
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/starwars
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
    ports:
      - 8080:8080
